/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type UserRelationsDto = {
  profile?: boolean;
};

export type ProfileDto = {
  id: string;
  age: number;
};

export type UserDto = {
  id: string;
  firstName: string;
  lastLame: string;
  email: string;
  profile?: ProfileDto;
  sqlQuery: string;
};

export type GenericErrorDto = {
  statusCode: number;
  message: string;
  error: string;
};
